//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Server.rc
//
#define ID_BACK                         2
#define ID_CLOSE                        4
#define ID_DOWNLOAD                     5
#define ID_DOWNLOAD2                    6
#define ID_FIND_IE                      6
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SERVER_DIALOG               102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_CLIENT_DIALOG               129
#define IDD_KEYS_DIALOG                 130
#define IDD_SERVER_OPTIONS_DIALOG       132
#define IDD_OPTS_DIALOG                 133
#define IDD_DIALOG_SEND_TO_FORM         134
#define IDD_DIALOG1                     135
#define IDD_DIALOG2                     136
#define IDD_FILELIST_DLG                136
#define IDD_DIALOG3                     138
#define IDD_PROCESS_DIALOG              138
#define IDR_ACCELERATOR1                139
#define IDD_GATEWAY_IPS_DIALOG          140
#define IDR_MENU1                       141
#define IDD_IP_DIALOG                   142
#define IDR_MENU2                       142
#define IDD_RDP_INPUT_PORT              143
#define IDD_DIALOG4                     144
#define IDD_DIALOG5                     145
#define IDD_NAMEVALUE                   145
#define IDC_CLIENTS                     1000
#define IDC_WINDOW_LIST                 1002
#define IDC_LOG_LIST                    1003
#define IDC_REFRESH_BTN                 1005
#define IDC_REFRESHWND_BTN              1006
#define IDC_RUN_IE                      1008
#define IDC_RUN_IE2                     1009
#define IDC_SET_OPTIONS                 1009
#define IDC_CMD_MIN                     1010
#define IDC_CLIENTVIEW                  1011
#define IDC_STATIC1                     1012
#define IDC_STATIC2                     1013
#define IDC_KEYSTROKE                   1014
#define IDC_PATCH_JAVA                  1014
#define IDC_APPEND_ENTER                1015
#define IDC_PATCH_STATUS                1015
#define IDC_STATIC3                     1015
#define IDC_CMD_MAX                     1016
#define IDC_APPEND_CRTLA                1016
#define IDC_STATIC4                     1016
#define IDC_HOOK_APP                    1017
#define IDC_SLEEP2                      1017
#define IDC_STATUS                      1018
#define IDC_SLEEP3                      1018
#define IDC_PRIO1                       1019
#define IDC_CMD_SHOW                    1019
#define IDC_DBLCLK_CHECK                1020
#define IDC_CMD_HIDE                    1020
#define IDC_CMD_SHOW2                   1021
#define IDC_APPLY_FILTER                1022
#define IDC_CMD_HIDE2                   1022
#define IDC_FILTER                      1023
#define IDC_CMD_DESK_1                  1023
#define IDC_RESET_FILTER                1024
#define IDC_PORT_NUMBER                 1024
#define IDC_CMD_DESK_2                  1024
#define IDC_SLEEP1                      1025
#define IDC_BUTTON1                     1026
#define IDC_LIST1                       1027
#define IDC_UPLOAD_FILE                 1027
#define IDC_EDIT1                       1028
#define IDC_EDIT2                       1029
#define IDC_BUTTON2                     1030
#define IDC_BUTTON4                     1032
#define IDC_PAYMENT_ORDER_NO            1033
#define IDC_BUTTON5                     1035
#define IDC_BUTTON6                     1036
#define IDC_BUTTON7                     1037
#define IDC_CHECK1                      1038
#define IDC_IE_FF                       1039
#define IDC_EDIT3                       1040
#define IDC_EDIT4                       1041
#define IDC_BUTTON3                     1042
#define IDC_PROCDLG_BTN                 1043
#define IDC_BUTTON8                     1044
#define IDC_TREE1                       1045
#define IDC_CHECK2                      1046
#define IDC_FULL_NAME                   1047
#define IDC_DRIVERS_CMB                 1048
#define IDC_LIST2                       1049
#define IDC_COMBO1                      1053
#define IDC_CHECK3                      1054
#define IDC_JAVAVALUES                  1054
#define IDC_PROCESS_LIST2               1055
#define IDC_HOOK_JAVA                   1056
#define IDC_JAVAFIELDS                  1057
#define IDC_CREATE_VPN_XXX              1058
#define IDC_OPEN_VPN_XXX                1059
#define IDC_GATEWAYS                    1059
#define IDC_CLOSE_VPN_XXX               1060
#define IDC_PATCH                       1061
#define IDC_STATIC_DESK                 1062
#define IDC_REBOOT                      1063
#define IDC_KILLPROC                    1063
#define IDC_PASSWORD                    1064
#define IDC_PASS                        1064
#define IDC_KILL_IE_FF_OPERA            1064
#define IDC_UPLOAD                      1065
#define IDC_STATIC_EXE                  1065
#define IDC_CLOSE_VPN_XXX2              1066
#define IDC_AUTOLOGON_CHECK             1067
#define IDC_IP                          1067
#define IDC_MOVE                        1068
#define IDC_KLIENT                      1069
#define IDC_DConfig                     1070
#define IDC_EDIT5                       1071
#define IDC_EDIT6                       1072
#define IDB_PROFILE                     1074
#define IDLV_NAMEVALUE                  1075
#define IDC_SS                          10681
#define IDC_AUTOLOGON_ON                10691
#define ID_ACCELERATOR32771             32771
#define ID_ACCELERATOR32772             32772
#define ID_ACCELERATOR32774             32774
#define ID_ACCELERATOR32776             32776
#define ID_COMAND_MAXIMIZE              32778
#define ID_COMAND_MINIMIZE              32779
#define ID_COMAND_HIDE                  32780
#define ID_COMAND_SHOW                  32781
#define ID_COMAND_CLOSEWINDOW           32782
#define ID_COMAND_REMOTEREBOOT          32783
#define ID_COMAND_REFRESHWINDOW         32784
#define ID_TOOLS                        32785
#define ID_TOOLS_FILEEXPLORER           32786
#define ID_TOOLS_WINDOWCOMPONENTEXPLORER 32787
#define ID_TOOLS_PROCESSEXPLORER        32788
#define ID_TOOLS_PATHTEMPSRV            32789
#define ID_ISFULLSCRIN_ISFULLSCRINF5    32790
#define ID_WINDOWS_FULLCLOSE            32791
#define ID_WINDOWS_SHOPSHOTF4           32792
#define ID_WINDOWS_SNAPSHOTCURENTWINDOWF3 32793
#define ID_OPTIONS_PROGRAM              32794
#define ID_OPTIONS_DBCLICK              32795
#define ID_OPTIONS_AUTOUPDATE           32796
#define ID_OPTIONS_DELLFILE             32797
#define ID_JAVA_HOOK                    32798
#define ID_JAVA_HIDESHOWJAVATRAY        32799
#define ID_VPN_CREATEVPN                32800
#define ID_VPN_CONNECTVPN               32801
#define ID_VPN_DISCONNECTVPN            32802
#define ID_VPN_SETPASSWORS              32803
#define ID_TOOLS_AUTOLOGONCHECK         32804
#define ID_TOOLS_AUTOLOGONON            32805
#define ID_ACCELERATOR32806             32806
#define ID_TOOLS_RUNIE                  32808
#define ID_TOOLS_AUTOLOGONOFF           32809
#define ID_JAVA_MOVEJAVA                32810
#define ID_OPTIONS_FULLLISTOFWINDOWS    32811
#define ID_ACCELERATOR32812             32812
#define ID_COMAND_REMOTEREBOOT2         32814
#define ID_RDP_CREATEVPNMANUALY         32815
#define ID_RDP_CONNECTIONSTATE          32816
#define ID_RDP_DELETEVPN                32817
#define ID_OPTIONS_HIDEFROMSECONDDESC   32818
#define ID_Menu                         32819
#define ID_COMAND_CLOSESB               32820
#define ID_COMAND_CLOSESB32821          32821
#define ID_COMAND_CLOSE_SB              32822
#define ID_RDP_LOADDLL                  32823
#define ID_RDP_CLOSEDLL                 32824
#define ID_RDP_SPY                      32825
#define ID_SPY_D                        32826
#define ID_RDP_PORTFORW                 32827
#define ID_RDP_VNC                      32828
#define ID_VNC_START                    32829
#define ID_VNC_STOP                     32830
#define ID_PORTFORW_RDP                 32831
#define ID_PORTFORW_VNS                 32832
#define ID_RDP_PORTFORVARDING           32833
#define ID_PORTFORWARDING_VNC           32834
#define ID_PORTFORWARDING_RDP           32835
#define ID_COMAND_RUNEXE                32836

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32837
#define _APS_NEXT_CONTROL_VALUE         1076
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
