/* List of defines generated by configure. Included with preprocessor flag,
 * -include, to avoid long list of -D defines on the compile command-line.
 * Do not edit.
 */

#ifndef _MOZILLA_CONFIG_H_
#define _MOZILLA_CONFIG_H_

#define ACCESSIBILITY 1
#define D_INO d_ino
#define HAVE_ATLBASE_H 1
#define HAVE_MMINTRIN_H 1
#define HAVE_OLEACC_IDL 1
#define HAVE_SNPRINTF 1
#define HAVE_UINT64_T 1
#define HAVE_WPCAPI_H 1
#define HW_THREADS 1
#define IBMBIDI 1
#define MOZILLA_VERSION "1.9.1.3"
#define MOZILLA_VERSION_U 1.9.1.3
#define MOZ_BUILD_APP xulrunner
#define MOZ_CRASHREPORTER 1
#define MOZ_CRASHREPORTER_ENABLE_PERCENT 100
#define MOZ_DEFAULT_TOOLKIT "cairo-windows"
#define MOZ_DISTRIBUTION_ID "org.mozilla"
#define MOZ_DLL_SUFFIX ".dll"
#define MOZ_EMBEDDING_LEVEL_BASIC 1
#define MOZ_EMBEDDING_LEVEL_DEFAULT 1
#define MOZ_EMBEDDING_LEVEL_MINIMAL 1
#define MOZ_ENABLE_CANVAS 1
#define MOZ_ENABLE_LIBXUL 1
#define MOZ_FEEDS 1
#define MOZ_JSLOADER 1
#define MOZ_LOGGING 1
#define MOZ_MATHML 1
#define MOZ_MEDIA 1
#define MOZ_MEMORY 1
#define MOZ_MEMORY_SIZEOF_PTR_2POW 2
#define MOZ_MEMORY_WINDOWS 1
#define MOZ_MORKREADER 1
#define MOZ_NO_XPCOM_OBSOLETE 1
#define MOZ_OGG 1
#define MOZ_PLACES 1
#define MOZ_PROFILELOCKING 1
#define MOZ_RDF 1
#define MOZ_STORAGE 1
#define MOZ_SVG 1
#define MOZ_SYDNEYAUDIO 1
#define MOZ_TREE_CAIRO 1
#define MOZ_UPDATE_CHANNEL default
#define MOZ_USER_DIR "Mozilla"
#define MOZ_VIEW_SOURCE 1
#define MOZ_WAVE 1
#define MOZ_XPINSTALL 1
#define MOZ_XTF 1
#define MOZ_XUL 1
#define MOZ_XULRUNNER 1
#define MOZ_XUL_APP 1
#define NO_X11 1
#define NS_PRINTING 1
#define NS_PRINT_PREVIEW 1
#define OJI 1
#define STDC_HEADERS 1
#define WIN32 1
#define WIN32_LEAN_AND_MEAN 1
#define WINVER 0x500
#define XP_WIN 1
#define XP_WIN32 1
#define X_DISPLAY_MISSING 1
#define _CRT_NONSTDC_NO_DEPRECATE 1
#define _CRT_SECURE_NO_DEPRECATE 1
#define _STATIC_CPPLIB 1
#define _WIN32 1
#define _WIN32_IE 0x0500
#define _WIN32_WINNT 0x500
#define _WINDOWS 1
#define _X86_ 1

#endif /* _MOZILLA_CONFIG_H_ */

